-- Royal Shine & SMILE Dental Care
-- Run this script in Supabase Dashboard -> SQL Editor.

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 2 and 120),
  phone text not null check (char_length(btrim(phone)) between 7 and 30),
  treatment text not null default 'General consultation',
  appointment_date date not null,
  appointment_time time without time zone not null,
  message text,
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'completed', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists appointments_date_idx
  on public.appointments (appointment_date, appointment_time);

create index if not exists appointments_status_idx
  on public.appointments (status);

alter table public.appointments enable row level security;

-- The website uses the public/publishable Supabase key to submit requests.
-- Visitors can create appointments, but cannot read, edit, or delete them.
drop policy if exists "Anyone can submit appointments" on public.appointments;
create policy "Anyone can submit appointments"
  on public.appointments
  for insert
  to anon, authenticated
  with check (true);

-- Keep updated_at current when a staff member changes an appointment.
create or replace function public.set_appointments_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists appointments_set_updated_at on public.appointments;
create trigger appointments_set_updated_at
  before update on public.appointments
  for each row
  execute function public.set_appointments_updated_at();

-- Explicit grants required by Supabase's REST API.
grant insert on table public.appointments to anon, authenticated;

-- Optional sample query for clinic staff using the Supabase dashboard:
-- select * from public.appointments order by appointment_date, appointment_time;
